version: '3.8'
services:
  autonomous_mission:
    image: "easy_walk_short:arm64" # Nuovo nome dell'immagine!
    network_mode: "host"
    volumes:
      - ./graph:/app/graph
      - ./MissionMap:/app/MissionMap
      - ./MissionLogs:/app/MissionLogs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "1024m"
    oom_score_adj: 1000